services:
  - type: web
    name: neko-manga-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: NUMERO_ADMIN
        sync: false
      - key: PORT
        value: 10000
